[project]
name = "eagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "liuyan", email = "lyfx99@icloud.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
eagent = "eagent:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
